# version: '3.7'

services:
  humble_gazebo:
    build:
      context: .
      shm_size: '10gb'
      dockerfile: Dockerfile
      target: gazebo
    image: humble_gazebo:latest
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [" GPU-d088c2f1-1918-4eff-8f6c-991749db7c76"]
              capabilities: [gpu]
    volumes:
      - ./:/workspace
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    container_name: humble_gazebo_container
    # runtime: nvidia
    environment:
      DISPLAY: 172.20.144.1:0.0
      # QT_X11_NO_MITSHM: 1
      NAMESPACE: $NAMESPACE
    tty: true
